language: node_js


# disabled, because osx takes very long
#os:
#  - linux
#  - osx

node_js:
  - "6"

# 20180208: build failed with weird syntax errors from "tsc"
#cache:
#  directories:
#    - node_modules

install:
  - npm install

script:
- npm run test
