
# build is disabled because it expects MS Visual Studio solution file
build: off

version: '{build}'

environment:
  nodejs_version: "8.9.4"
  apiUrl : "https://ci.appveyor.com/api"

cache:
  - node_modules -> package.json

install:
  - ps: $apiUrl
  - ps: Install-Product node $env:nodejs_version
  - ps: Install-Product yarn
  - yarn -g install npm
  - yarn install
  
test_script:
  - node --version
  - yarn --version
  - yarn test
