
# build is disabled because it expects MS Visual Studio solution file
build: off

version: '{build}'

environment:
  nodejs_version: "6.9.0"
  apiUrl : "https://ci.appveyor.com/api"

#cache:
#  - node_modules -> package.json

install:
  - ps: $apiUrl
  - ps: Install-Product node $env:nodejs_version
  - npm install npm
  - .\node_modules\.bin\npm install

test_script:
  - node --version
  - .\node_modules\.bin\npm --version
  - .\node_modules\.bin\npm test
