
# build is disabled because it expects MS Visual Studio solution file
build: off

version: '{build}'

environment:
  nodejs_version: "6.9.0"
  apiUrl : "https://ci.appveyor.com/api"

# 20180208: build failed with weird syntax errors from "tsc"
#cache:
#  - node_modules -> package.json

install:
  - ps: $apiUrl
  - ps: Install-Product node $env:nodejs_version
  - npm -g install npm
  - npm install
  
test_script:
  - node --version
  - npm --version
  - npm test
